#!/usr/bin/env python3
"""Bounded WSL QA against ./rusty-sand, never the bundled demo executable.

Run: python3 tests/qa/wsl_surface.py --release --evidence-dir /absolute/external/path
Use --compile-only to compile without launching any target or production code.
Python 3.11+, Linux pidfds, WSL interop, wslpath, Windows PowerShell, an existing
MinGW compiler and an already-built launcher/exe/DLL are assumed. No installs or
Cargo builds are performed. --release uses the launcher's release default;
without it, --launcher-debug selects debug explicitly. The launcher
owns executable/workdir/output path conversion; fixture arguments after -- are
converted explicitly with wslpath because the launcher must not rewrite them.

No production prompt sentinel currently exists. Interactive cases are PENDING
unless --manual or BOTH --startup-marker and --hook-marker are supplied. Tokens
must be integration-owned machine markers, not human sentences. With --manual,
watch the mirrored real terminal, type `startup` then Enter AFTER startup input
is ready, and `hook` then Enter AFTER hook input is ready. These stage lines go
to the harness, not the target; the harness then sends the scenario's Y/N/EOT/
Ctrl-C. Do not queue stage lines. This is an operator readiness hook, not an
automated rendering assertion. Screenshots remain the parent's responsibility.

Each invocation retains full logs, JSON reports and results.json in a new run
directory under the requested external evidence directory. Compiled executables,
markers and runtime output are private temporary files and are removed. Cleanup
first stops native rusty_sand.exe instances whose command line contains the
unique fixture filename, then runs the fixture's exact-image cleanup. Any forced
native recovery is a FAIL, not a passing lifecycle assertion. Exit 0 means all
selected checks passed, 1 means FAIL, 2 means PENDING (never implicit success).
"""

from __future__ import annotations

import argparse
import json
import os
import signal
import shutil
import subprocess
import sys
import tempfile
import traceback
import uuid
from pathlib import Path

# The documented invocation must not leave generated bytecode in the checkout.
sys.dont_write_bytecode = True

from pty_session import PtySession
from surface_checks import ARGUMENTS, AUTOMATIC, INTERACTIVE, check_outcome

ROOT = Path(__file__).resolve().parents[2]
COMPILER = Path("/home/davic/.local/opt/mingw-gcc/usr/bin/x86_64-w64-mingw32-gcc")
POWERSHELL = Path("/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe")

def command_output(command: list[str], timeout: float, log: Path) -> bytes:
    """Retain complete stdout/stderr, including command failures and timeouts."""
    with log.open("wb") as transcript:
        transcript.write((json.dumps(command) + "\n").encode())
        transcript.flush()
        with subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                              start_new_session=True) as child:
            try:
                output, _ = child.communicate(timeout=timeout)
            except (subprocess.TimeoutExpired, KeyboardInterrupt):
                os.killpg(child.pid, signal.SIGKILL)
                output, _ = child.communicate(timeout=5)
                transcript.write(output)
                raise
            transcript.write(output)
            if child.returncode != 0:
                raise subprocess.CalledProcessError(child.returncode, command, output)
            return output

def windows_path(path: Path, evidence: Path) -> str:
    return command_output(["wslpath", "-w", str(path)], 10, evidence).decode().strip()

def native_cleanup(fixture: Path, evidence: Path, label: str) -> list[str]:
    """Recover only uniquely identified owned Windows processes and report leaks."""
    # The fixture filename is generated by us (ASCII UUID), not caller input.
    script = (
        "$ErrorActionPreference='Stop'; $count=0; "
        "Get-CimInstance Win32_Process -Filter \"Name = 'rusty_sand.exe'\" | "
        f"Where-Object {{ $_.CommandLine -and $_.CommandLine.Contains('{fixture.name}') }} | "
        "ForEach-Object { $p=Get-Process -Id $_.ProcessId -ErrorAction Stop; "
        "$p.Kill(); if (!$p.WaitForExit(5000)) { throw 'owned launcher did not exit' }; "
        "$count++ }; @{killed=$count} | ConvertTo-Json -Compress"
    )
    failures = []
    try:
        raw = command_output(
            [str(POWERSHELL), "-NoProfile", "-NonInteractive", "-Command", script],
            20, evidence / f"{label}-launcher-cleanup.log",
        )
        value = json.loads(raw.decode("utf-8-sig"))
        if not isinstance(value, dict) or type(value.get("killed")) is not int or value["killed"] != 0:
            failures.append(f"native launcher recovery required: {value!r}")
    except (OSError, ValueError, subprocess.SubprocessError) as error:
        failures.append(f"native launcher cleanup failed: {error}")

    try:
        raw = command_output([str(fixture), "--cleanup"], 20, evidence / f"{label}-fixture-cleanup.log")
        value = json.loads(raw)
        if value != {"killed": 0, "status": 0}:
            failures.append(f"native fixture recovery required: {value!r}")
    except (OSError, ValueError, subprocess.SubprocessError) as error:
        failures.append(f"native fixture cleanup failed: {error}")
    return failures

def drive(session: PtySession, name: str, args: argparse.Namespace) -> None:
    startup = args.startup_marker.encode() if args.startup_marker else None
    hook = args.hook_marker.encode() if args.hook_marker else None
    session.ready(startup, "startup")
    if name.endswith("startup"):
        if name.startswith("eof-"):
            session.send(b"\x04")
        elif name.startswith("ctrl-c-"):
            session.send(b"\x03")
        return

    cursor = session.send(b"Y\n")
    session.ready(hook, "hook", cursor)
    if name.startswith("eof-"):
        session.send(b"\x04")
    elif name.startswith("ctrl-c-"):
        session.send(b"\x03")
    elif name != "deadline-hook":
        session.send(b"N\n" if name == "deny" else b"Y\n")

def scenario(name: str, fixture: Path, work: Path, evidence: Path, args: argparse.Namespace) -> dict:
    directory = work / name
    directory.mkdir()
    marker = directory / "marker with spaces.json"
    reports = directory / "reports"
    reports.mkdir()
    marker_windows = windows_path(marker, evidence / f"{name}-wslpath.log")
    command = [str(args.launcher.resolve())]
    if not args.release:
        command.append("--launcher-debug")
    command += [str(fixture), "--workdir", str(directory), "--output", str(reports),
                "--format", "both", "--timeout", str(args.target_timeout),
                "--no-behavior-detection"]
    if name in AUTOMATIC:
        command.append("--no-interactive")
    if name == "plain":
        command.append("--plain")
    if name == "color-never":
        command.extend(["--color", "never"])
    if name == "reduced-motion":
        command.append("--reduced-motion")
    command.append("--")
    if name == "arguments":
        command += ["--args", marker_windows, *ARGUMENTS]
    else:
        if name in ("wait-deadline", "reduced-motion"):
            command.append("--wait")
        command.append(marker_windows)

    env = os.environ.copy()
    env["TERM"] = "xterm-256color"
    env.pop("NO_COLOR", None)
    env.pop("CLICOLOR_FORCE", None)
    if name == "no-color":
        env["NO_COLOR"] = "1"
    result = {"name": name, "status": "FAIL", "command": command, "failures": []}
    log = evidence / f"{name}.terminal.log"
    try:
        if name == "redirected":
            with log.open("wb") as output:
                with subprocess.Popen(command, cwd=ROOT, env=env, stdin=subprocess.DEVNULL,
                                      stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                                      start_new_session=True) as child:
                    try:
                        data, _ = child.communicate(timeout=args.timeout)
                    except (subprocess.TimeoutExpired, KeyboardInterrupt):
                        os.killpg(child.pid, signal.SIGKILL)
                        data, _ = child.communicate(timeout=5)
                        output.write(data)
                        raise
                    output.write(data)
                    code = child.returncode
        else:
            with PtySession(command, log, cwd=ROOT, env=env, timeout=args.timeout,
                            manual_fd=sys.stdin.fileno() if args.manual and name in INTERACTIVE else None,
                            mirror=sys.stdout.buffer if args.manual else None) as session:
                if name in INTERACTIVE:
                    if args.manual:
                        print(f"\nQA {name}: signal startup/hook readiness only after observing it.", flush=True)
                    drive(session, name, args)
                code = session.finish()
                data = bytes(session.output)

        result["launcher_exit"] = code
        result["failures"] += check_outcome(name, code, data, marker, reports / "report.json")
        result["marker_exists"] = marker.exists()
        if marker.exists():
            result["marker_hex"] = marker.read_bytes().hex()
    except Exception:
        # This scenario boundary retains the full failure and proceeds to the
        # independent cases; it never changes an exception into a passing result.
        result["failures"].append(traceback.format_exc())
    finally:
        result["failures"] += native_cleanup(fixture, evidence, name)
        if (reports / "report.json").exists():
            shutil.copyfile(reports / "report.json", evidence / f"{name}.report.json")

    result["status"] = "FAIL" if result["failures"] else "PASS"
    return result

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--release", action="store_true")
    parser.add_argument("--evidence-dir", type=Path, required=True)
    parser.add_argument("--launcher", type=Path, default=ROOT / "rusty-sand")
    parser.add_argument("--compiler", type=Path, default=COMPILER)
    parser.add_argument("--compile-only", action="store_true")
    parser.add_argument("--manual", action="store_true")
    parser.add_argument("--startup-marker")
    parser.add_argument("--hook-marker")
    parser.add_argument("--timeout", type=float, default=45)
    parser.add_argument("--target-timeout", type=int, default=10)
    parser.add_argument("--scenario", action="append", choices=AUTOMATIC + INTERACTIVE)
    args = parser.parse_args()
    evidence_root = args.evidence_dir.resolve()
    if evidence_root == ROOT or ROOT in evidence_root.parents:
        parser.error("evidence must be outside the repository")
    if not (0 < args.target_timeout < args.timeout < 3600):
        parser.error("require 0 < target-timeout < timeout < 3600")
    if bool(args.startup_marker) != bool(args.hook_marker):
        parser.error("supply both machine markers, or use --manual")
    if args.scenario and len(set(args.scenario)) != len(args.scenario):
        parser.error("each scenario may only be selected once")
    evidence_root.mkdir(parents=True, exist_ok=True)
    evidence = Path(tempfile.mkdtemp(prefix="surface-", dir=evidence_root))
    results = []
    selected = [] if args.compile_only else list(args.scenario or AUTOMATIC + INTERACTIVE)
    try:
        with tempfile.TemporaryDirectory(prefix="runtime-", dir=evidence) as temporary:
            work = Path(temporary)
            fixture = work / f"qa-{uuid.uuid4().hex}.exe"
            command = [str(args.compiler), "-std=c11", "-municode", "-O2", "-Wall", "-Wextra",
                       "-Werror", str(ROOT / "tests/fixtures/windows_surface.c"), "-o", str(fixture)]
            command_output(command, 60, evidence / "compile.log")
            results.append({"name": "compile", "status": "PASS", "command": command, "exit": 0})
            if not args.compile_only:
                for name in selected:
                    if not args.launcher.is_file():
                        results.append({"name": name, "status": "PENDING", "reason": "launcher not present"})
                    elif name in INTERACTIVE and not (args.manual or args.startup_marker):
                        results.append({"name": name, "status": "PENDING", "reason": "needs manual readiness or stable machine tokens"})
                    else:
                        results.append(scenario(name, fixture, work, evidence, args))
    except (Exception, KeyboardInterrupt):
        results.append({"name": "harness", "status": "FAIL", "failures": [traceback.format_exc()]})
    finally:
        completed = {result["name"] for result in results}
        for name in selected:
            if name not in completed:
                results.append({"name": name, "status": "PENDING", "reason": "harness stopped before completion"})
        summary = {"results": results, "evidence": str(evidence)}
        (evidence / "results.json").write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
        print(json.dumps(summary, indent=2))

    statuses = {result["status"] for result in results}
    if "FAIL" in statuses or not statuses <= {"PASS", "PENDING"}:
        return 1
    return 2 if "PENDING" in statuses else 0


if __name__ == "__main__":
    raise SystemExit(main())
